### ISSUE TITLE
New file template contains invalid content

### ISSUE THREAD

**Issue by raducoravu** [TEIC/oxygen-tei#11]
When the framework zip is produced, there is a new file template in:
templates\TEI P5\Feature Structures.xml

which is invalid. Also it is not a very good new file template. New File templates should be used as a starting point for the end user and should be terse. So they are not samples of what can be done with a certain vocabulary.

**Comment by lb42** [comment]
Thanks for reporting this! The template has been made simply by copying the little test file isofs.tei, but the latter was invalid. I've corrected both. I agree that the template file could be improved...

**Comment by raducoravu** [comment]
👍 No problem, we recently created an automated test in Oxygen to test all new file templates which ship with the application and this template was flagged as not valid TEI.

**Comment by lb42** [comment]
Valid against what though? isofs.tei is valid against the schema generated from isofs.odd, which is not the same as TEI all (it has a different set of start elements)

**Comment by raducoravu** [comment]
The current "Feature Structures.xml" TEI P5 file template distributed with Oxygen 18.1 in "OXYGEN_INSTALL_DIR\frameworks\tei\templates\TEI P5" has the content:

			<?xml version="1.0" encoding="UTF-8"?>
			<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/isofs.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
			<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/isofs.rng" type="application/xml"
				schematypens="http://purl.oclc.org/dsdl/schematron"?>
			<fLib xmlns="http://www.tei-c.org/ns/1.0">
						
			  <f name="xxx">A feature may have untyped content</f>
			  <f name="yyy">
				  <string>or typed</string>
			   </f>
			  <f name="notgood">
				  <string>multiple types</string>
				  <symbol value="doubleplusungood"/>
			  </f>
			  <f name="alsonotgood">mixed content
			  <symbol value="doubleplusungood"/>
			  </f>
			</fLib>

The last 2 "f" elements are reported as invalid according to the schema "OXYGEN_INSTALL_DIR\frameworks\tei\xml\tei\custom\schema\relaxng\isofs.rng"

**Comment by lb42** [comment]
I  checked a corrected version into the tei repo about an hour ago

**Comment by lb42** [comment]
Apologies: I pushed version of template file which was valid against TEI All instead of isofs. Fixed now, so closing.
