### ISSUE TITLE
Need to make validation sensitive to `TEI/@version`

### ISSUE THREAD

**Issue by martindholmes** [TEIC/oxygen-tei#17]
As we have increasing numbers of deprecations, the ability to specify `@version` on the `<TEI>` element and have Oxygen automatically pull the correct version of the schema against which to validate becomes more important. We need to figure out how to configure the document type to do this.

**Comment by raducoravu** [comment]
But doesn't each TEI document have an xml-model PI point to its used schema?

If not you could have a base TEI-BASE document type association which has no association rules.
Then extend (there is an Extend button in the Document Type Associations page) that base framework and each extension adds a specific association rule base on that certain version attribute being a certain value and it would also specify a default schema used for validation and content completion.

As an alternative I'm not sure if the NVDL language has support to validate a document with one schema or another depending on a certain attribute value but this could be looked into.

**Comment by martindholmes** [comment]
You're right; I'm misreading the purpose of `@version` here. This ticket is nonsense. Too early in the morning, no coffee yet. :-)
