### ISSUE TITLE
Should we switch all TEI plugin conversions to use only Saxon HE?

### ISSUE THREAD

**Issue by martindholmes** [TEIC/oxygen-tei#19]
In Issue #14, we discovered that an obscure bug was triggered by the use of one of the commercial versions of Saxon, combined with some optimizations which Oxygen provides for those versions. We worked around the bug by removing the oxygen.jar file from the additional libs in those transformations; this has the effect of making the transformation fall back to Saxon HE, which worked fine.

Since all of our testing uses Saxon HE, and we now know that there's some risk of errors arising out of the optimizations provided for the other versions, should we now make a policy decision to switch all TEI conversions to Saxon HE? Presumably there would be some performance penalty, but it would mean that our testing and the plugin processing are more closely aligned.

**Comment by raducoravu** [comment]
As long as you are not using any Java extensions in the XSLTs indeed you can configure all the XSLT transformation scenarios to use Saxon HE.

**Comment by martindholmes** [comment]
@raducoravu I see in src/ro/sync/ecss/extensions/common/operations/XQueryOperation.java:

`return authorAccess.getXMLUtilAccess().createXQueryTransformer(xquerySrc, null, AuthorXMLUtilAccess.TRANSFORMER_SAXON_PROFESSIONAL_EDITION, false);`

If I replace this with:

`return authorAccess.getXMLUtilAccess().createXQueryTransformer(xquerySrc, null, AuthorXMLUtilAccess.TRANSFORMER_SAXON_HOME_EDITION, false);`

would you expect any problems?

**Comment by raducoravu** [comment]
@martindholmes XQuery operations require Saxon enterprise edition, so changing to TRANSFORMER_SAXON_HOME_EDITION will make the operation not work (although the operation is not used from what I remember anywhere in the TEI framework custom actions).

I think this entire Java package can be removed from the TEI framework JAR and from the repository:
https://github.com/TEIC/oxygen-tei/tree/master/oxygen-tei/frameworks/tei/src/ro/sync/ecss/extensions/commons
The package is also present in the main oxygen.jar and when needed will be loaded from the oxygen.jar.
If the package is present in the tei extensions JAR, it will be loaded with priority from the TEI framework.
Or remove the XQueryOperation in particular from the TEI extension Java sources, and it will be loaded from the main oxygen.jar where it uses an internal API to create a Saxon EE engine.

**Comment by raducoravu** [comment]
@AlexJitianu signaled to me we have two default Author operations, an XQUeryUpdateOperation (which absolutely requires Saxon EE) and an XQueryOperation which works with Saxon HE but it depends on the XQuery script really, as the script might contain constructs which work only with EE and not with HE. The TEI framework does not use (yet) any of these operations for TEI specific actions so it does not matter if you make changes to them and switch them to HE.

Or you could attempt to remove the entire "commons" Java package from the TEI extensions jar and as I said before the TEI framework should take the common actions from the main Oxygen jar. But if this is done we would need to check if the TEI framework still supports the oldest Oxygen version that it officially states as being supported.
Having a copy of the "ro/sync/ecss/extensions/commons" package on your side gives you more stability if the common operations get modified in each Oxygen release, but in a way this copy is redundant and whenever we make changes to the base operations we try to make sure they are backwards compatible.

**Comment by martindholmes** [comment]
Thank indeed @raducoravu. I'll leave everything alone for the moment, then!
