### ISSUE TITLE
New file template properties not generated correctly

### ISSUE THREAD

**Issue by raducoravu** [TEIC/oxygen-tei#22]
In the distributed TEI framework there are numerous file templates like:

         templates\TEI P5\All plus SVG and MathML.xml

and each of them has a ".properties" pair file like "All plus SVG and MathML.properties" which in this case contains:

			<?xml version="1.0" encoding="UTF-8"?>
			smallIcon=../icons/TEI_16.gif
			bigIcon=../icons/TEI_48.png

These properties files seem to be created automatically. There are two problems, the xml declaration processing instruction header should be removed as it is not an XML file and an extra key, value pair should be added at the end of each properties file:

          type=general

We need that to differentiate between DITA and non-DITA new file templates.

**Comment by martindholmes** [comment]
Thanks Radu. Please feel free to make this change, or assign it to me.

**Comment by raducoravu** [comment]
I looked a little bit but I did not find where the XSLT stylesheet which generates the properties files is. Is it in this project or somewhere in the set of resources downloaded from sourceforge?

**Comment by AlexJitianu** [comment]
The templates are copied from https://sourceforge.net/projects/tei/files/TEI-P5-all/tei-3.2.0.zip . They are located in the directory "xml/tei/custom/templates". This means that they are generated in the project from which tei-3.2.0.zip is built.

**Comment by martindholmes** [comment]
Sorry, yes. That's my job, then. I'll raise a ticket on the TEI repo.

**Comment by martindholmes** [comment]
I believe this is all fixed now; current versions of the templates do not have the XML declarations.
