### ISSUE TITLE
can't install / update TEI framework in Oxygen due to server error (bits.nsms.ox.ac.uk:8080)

### ISSUE THREAD

**Issue by rvdb** [TEIC/oxygen-tei#28]
I can't update / install any of the tei-oxygen plugin frameworks from the Jenkins server (either stable or bleeding). A "connection reset" error is thrown when Oxygen is attempting to download the zip file mentioned in the update file (e.g. http://bits.nsms.ox.ac.uk:8080/job/oxygen-tei-bleeding/85/artifact/oxygen-tei/oxygen-tei-3.5.0a-7.46.0a-2018-09-08-074610.zip).

There seems to be a problem with the server where the zip files are hosted: http://bits.nsms.ox.ac.uk:8080 seems unreachable.

**Comment by martindholmes** [comment]
The Oxford server has been out of commission for a long time now. You can get the bleeding-edge plugin from:

https://teijenkins.hcmc.uvic.ca/job/oxygen-tei-bleeding/lastSuccessfulBuild/artifact/oxygen-tei/updateSite.oxygen

or from:

https://jenkins.tei-c.org/job/oxygen-tei-bleeding/lastSuccessfulBuild/artifact/oxygen-tei/updateSite.oxygen

**Comment by rvdb** [comment]
Hi @martindholmes , I am using the update file at jenkins.tei-c.org you've mentioned. Yet, inside that file, the zip file locations are specified as: 

    <xt:extension xmlns:local="http://teijenkins.hcmc.uvic.ca/ns" id="tei">
      <xt:location href="http://bits.nsms.ox.ac.uk:8080/job/oxygen-tei-bleeding/93/artifact/oxygen-tei/oxygen-tei-3.5.0a-7.46.0a-2018-09-10-071743.zip"/>
      <xt:version>3.5.31</xt:version>
      ...
    </xt:extension>

...and the failure to download the files from that location makes the update / installation process choke in Oxygen.

**Comment by jamescummings** [comment]
Eek! No. You certainly shouldn't have that referencing bits.nsms.ox  ... in fact anything referencing ox.ac.uk as serving up TEIC  things should certainly be wiped. That should could meant to be pointing at the last successful version artifact or something?

**Comment by rvdb** [comment]
Ah, ok. I see now that there's a difference between both files:

- the update file at the Uvic server points to the same server for fetching the zip files:

    <xt:extension xmlns:local="http://teijenkins.hcmc.uvic.ca/ns" id="tei">
      <xt:location href="http://teijenkins.hcmc.uvic.ca/job/oxygen-tei-bleeding/21/artifact/oxygen-tei/oxygen-tei-3.5.0a-7.46.0a-2018-09-10-013340.zip"/>
      <xt:version>3.5.18</xt:version>
      ...
     </xt:extension>

  This is working correctly.

- the update file at the jenkins.tei-c.org server points to the bits.nms.ox.uk server for fetching the zip files:

    <xt:extension xmlns:local="http://teijenkins.hcmc.uvic.ca/ns" id="tei">
      <xt:location href="http://bits.nsms.ox.ac.uk:8080/job/oxygen-tei-bleeding/93/artifact/oxygen-tei/oxygen-tei-3.5.0a-7.46.0a-2018-09-10-071743.zip"/>
      <xt:version>3.5.31</xt:version>
      ...
    </xt:extension>

  This is not working.

So I guess there's a problem at the Paderborn Jenkins server?

**Comment by rvdb** [comment]
P.S.: note the different version numbers both files mention for the latest build of the extension, too...

**Comment by martindholmes** [comment]
This is partly the result of my server going down the other week, and @peterstadler's being promoted to jenkins.tei-c.org. We'll need to revisit the build file for the oxygen-tei plugin; I think it was originally written when only my Jenkins and the Oxford one existed. Stick with mine for the moment, till we get that fixed.

The version numbers will always be a bit different; they're based on Jenkins build job numbers, so they'll vary from server to server. As long as the same server is providing the plugin, though, it should have sensible version number sequences.

**Comment by rvdb** [comment]
Ok, thanks for clarifying, Martin.

**Comment by rvdb** [comment]
This seems to have been solved now: https://jenkins.tei-c.org/job/oxygen-tei-bleeding/lastSuccessfulBuild/artifact/oxygen-tei/updateSite.oxygen now points to the correct download location at the jenkins.tei-c.org server. Thanks for fixing!
