### ISSUE TITLE
Testing oXygen tei plugin

### ISSUE THREAD

**Issue by ebeshero** [TEIC/oxygen-tei#32]
@martindholmes Hi Martin! I suspect my issue is a fluke, because it's working for others with the current version of oXygen.  I'm using oXygen version 21, and having troubles with oXygen TEI plugins generally lately. Here's a screen capture of what happens when I try to test either of the two bleeding edge plugins you just updated: 
 

<img width="828" alt="Screenshot 2019-05-07 15 27 41" src="https://user-images.githubusercontent.com/4014518/57327509-2279c600-70dd-11e9-908b-52726b7a6023.png">

**Comment by martindholmes** [comment]
@ebeshero Is it possible that you have another version of the plugin installed already? That's the only thing I can think of. If so, try uninstalling all previous versions of the plugin from Help/Manage Add-ons. I've never seen that message before.

**Comment by ebeshero** [comment]
@martindholmes I'm trying that now...I've had this issue I think for at least a month now that I've noticed...

**Comment by ebeshero** [comment]
I see I have lots of different plugins for for TEI installed...I'm going to delete most of them, but hunting for the canonical locations I should be using...

**Comment by martindholmes** [comment]
I'm surprised you were able to install more than one version of the same plugin.

**Comment by ebeshero** [comment]
@martindholmes I deleted a bunch of old plugins--I must have been testing a bunch of these in the past year or two. Hmm. Your new bleeding-edge plugin is happily installing now...so far so good!

**Comment by ebeshero** [comment]
Okay: The bleeding edge plugin from here <https://jenkins.tei-c.org/job/oxygen-tei-bleeding/lastSuccessfulBuild/artifact/oxygen-tei/updateSite.oxygen>, installed just fine. 

But not-so-okay--when I tried this one: <https://teijenkins.hcmc.uvic.ca/job/oxygen-tei-bleeding/lastSuccessfulBuild/artifact/oxygen-tei/updateSite.oxygen>, it didn't fully install, and I saw an error to do with "premature end of file".

**Comment by martindholmes** [comment]
You uninstalled the other one first, right?

**Comment by ebeshero** [comment]
Yep. teijenkins was the first one I tried--didn't fully install. Tried the other and it worked. Uninstalled it and went back to teijenkins, and now seems to work. So okay--all is well! :-) I'll go try something with the plugin now.

**Comment by martindholmes** [comment]
I'll close this, then, and if you find any specific bugs in the functionality, you can raise tickets for them. Thanks for testing!
