### ISSUE TITLE
Update add-on to TEI 3.6.0 schemas

### ISSUE THREAD

**Issue by raducoravu** [TEIC/oxygen-tei#36]
One of our common end users would want to edit in Oxygen using the TEI 3.6.0 schemas:
https://www.oxygenxml.com/forum/post55711.html#p55711

**Comment by bwbohl** [comment]
I second this request!
It would be very nice if there was an update of the framework available, whenever there is a new release of https://github.com/TEIC/TEI or https://github.com/TEIC/Stylesheets

Thanks!

**Comment by martindholmes** [comment]
This has been available for a long time now. See the readme:
https://github.com/TEIC/oxygen-tei/blob/master/oxygen-tei-plugin.md
