### ISSUE TITLE
Release 11.0 missing from oXygen update site

### ISSUE THREAD

**Issue by bwbohl** [TEIC/oxygen-tei#42]
The latest Release unfortunately is missing from the TEI-C oXygen update site. It's a bit awkward as the release info page (https://www.tei-c.org/release/doc/tei-p5-doc/readme-4.0.0.html) includes a hint that 

> The documentation for updating the TEI Framework in oXygen to the latest release of the TEI Guidelines has been improved #1673 and added to the oxygen-tei repository, see How to automatically update your TEI framework in oXygen.

Which again https://www.tei-c.org/release/oxygen/updateSite.oxygen, that doesn't reference the latest release though :-/

**Comment by bwbohl** [comment]
cf. #31

**Comment by martindholmes** [comment]
We are at #14 now, so I don't think this is relevant.

**Comment by bwbohl** [comment]
and all previous releases seem to be there, too. Thanks!
