### ISSUE TITLE
logging is suppressed in latest Oxygen for tasks called via ANT targets

### ISSUE THREAD

**Issue by rvdb** [TEIC/oxygen-tei#48]
I've noticed how logging for the jTEI ANT transformation scenarios seems to have changed after Oxygen-20. Up to that version, logging was controlled with the file at https://github.com/TEIC/oxygen-tei/blob/83fe28a11fac160fba348dce57b58c8fe92f7756/oxygen-tei/frameworks/tei/xml/tei/jtei_aux/trans/log4j.properties. When calling a FOP transformation from a target in an ANT build file, this would catch all FOP output messages in the transformation output pane, providing very useful information about possible missing glyphs that need remediation when creating PDF files.

The current state of the oxygen-tei plugin (at https://github.com/TEIC/oxygen-tei/tree/83fe28a11fac160fba348dce57b58c8fe92f7756) seems to suppress this logging in Oxygen-23 and Oxygen-22. Yet, the same code is still producing FOP logging output in Oxygen-20 and Oxygen-19. Hence, I assume that after Oxygen-20 or Oxygen-21, something has changed w.r.t. logging. I do realize the setting `-Dlog4j2.disable.jmx=true` has been added to the ANT transformation scenarios in commit https://github.com/TEIC/oxygen-tei/commit/b5595661600d9735ed5e066a06c3147ae953a834, in response to issue https://github.com/TEIC/oxygen-tei/issues/45. 

I'm not sure if the latter change is responsible for the current suppression of logging in recent Oxygen versions, but I would like to find a way to re-enable logging. (I hope you don't mind me pinging you directly,  @AlexJitianu 😏  )

**Comment by DunaMariusCosmin** [comment]
Hi, 
In Oxygen, we use the Apache Log4j library for logging. Starting with version 22.1, we updated this library to version 2.  Log4j2 searches for a configuration file with the name "log4j2" and has a different configuration syntax: https://logging.apache.org/log4j/2.x/manual/configuration.html

I added a pull request (https://github.com/TEIC/oxygen-tei/pull/49) with this new configuration file. So, for versions 22.1 and 23, you have to edit this new file to configure the logging.

Regards,
Cosmin

**Comment by rvdb** [comment]
Thanks for clarifying, @DunaMariusCosmin . I've tested with the new properties file, but that doesn't make any difference in Oxygen-22+ (even when setting log level to "all"). I tried by explicitly declaring the properties file via the `-Dlog4j2.configuration` command line argument for the ANT task, but that didn't help either. Do you have an idea what else could be wrong?

Best,

Ron

**Comment by DunaMariusCosmin** [comment]
I think I found another problem. Please, add this element "<String>${framework(TEI P5)}/xml/tei/jtei_aux/trans/</String>" in the "transform-pdf" scenario from the "teip5jtei.framework" file, as I made in this commit: https://github.com/TEIC/oxygen-tei/pull/49/commits/7d937cf12debe2d38f200a010a74bfd682ea3dde

**Comment by rvdb** [comment]
Many thanks for your quick help, @DunaMariusCosmin , that seems to fix it! In order to get meaningful FOP output, the log level should be set to `WARN`; I've added that as a comment to your first commit, perhaps it's best to change that in your commit before merging (Git is not my area of expertise).

**Comment by martindholmes** [comment]
I've merged the commit, but I haven't done anything about the need for the comment; I'll leave that to @DunaMariusCosmin.

**Comment by DunaMariusCosmin** [comment]
I think we can set the level by default to "WARN". I made a pull request.

**Comment by martindholmes** [comment]
Thank you @DunaMariusCosmin ! I think we can close this now.
