### ISSUE TITLE
Can't build with recent Java versions

### ISSUE THREAD

**Issue by martindholmes** [TEIC/oxygen-tei#50]
Currently building the TEI framework successfully can only be done by switching to Java 1.8, or by swapping out a bunch of jars. We need to check with the Oxygen folks about whether it's possible to build with current Java versions (most of us are running 14 now), and if so, what we need to change to make that happen.

**Comment by raducoravu** [comment]
The main Oxygen application is still compiled to run with Java 1.8 or newer. If the Java content of the add-on does not have Java 9 or newer features used in it, you can try to use the "javac" with the "--release 8" flag maybe to force compilation with Java 8 compatibility but use the compiler from a newer hava version:
https://docs.oracle.com/en/java/javase/15/docs/specs/man/javac.html

**Comment by martindholmes** [comment]
@raducoravu Thanks indeed -- that seems to work fine with Java 14. I've added the flag in the frameworks build file. This will get propagated to our bleeding-edge test version today, so it'll be well tested in the next couple of weeks. The jar is very slightly larger built with a later javac, but that's not unusual. I'll close this if I don't see any problems in my own testing over the next couple of days.

**Comment by martinascholger** [comment]
@martindholmes: can we close the ticket?

**Comment by martindholmes** [comment]
@martinascholger Yes, sorry, I forgot to come back to it.
