### ISSUE TITLE
Oxygen 24.1 breaks transforms because we have Saxon 9 hard-coded

### ISSUE THREAD

**Issue by martindholmes** [TEIC/oxygen-tei#54]
Many of the standard transformations defined in our frameworks have:

`<String>${oxygenHome}/lib/*saxon*9*.jar</String>`

However, Oxygen 24.1 ships with Saxon 10, and now has the Saxon lib as:

`oxygen-patched-saxon-10.jar`

I'm going to try adding that alongside the existing one, so we maintain backwards compatibility, and see if that fixes it.

**Comment by martindholmes** [comment]
This works for Oxygen 24.1; will enlist other users to test for earlier versions.

**Comment by raducoravu** [comment]
@martindholmes fix looks good to me, we did the same thing in the TEI .framework files bundled with Oxygen 24.1

**Comment by martindholmes** [comment]
Thanks @Radu. I'll close this then. :-)

**Comment by raducoravu** [comment]
@martindholmes  Also all transformation scenarios in the "teip*.framework" files which contained references to:

      ${oxygenHome}/lib/*log4j*.jar

need to be changed to contain references to:

					<String>${oxygenHome}/lib/oxygen-patched-slf4j.jar</String>
					<String>${oxygenHome}/lib/logback-classic-*.jar</String>
					<String>${oxygenHome}/lib/logback-core-*.jar</String>
					<String>${oxygenHome}/lib/log4j-over-slf4j-*.jar</String>
                                        <String>${oxygenHome}/lib/log4j-to-slf4j-*.jar</String>
                                        <String>${oxygenHome}/lib/log4j-api-*.jar</String>

I'm attaching the changes we made in the TEI framework files in Oxygen 24.1
[tei.zip](https://github.com/TEIC/oxygen-tei/files/8388053/tei.zip)

**Comment by martindholmes** [comment]
@radu If I replace the original log4j with this collection, will things still work with older versions? I'm not sure how your patching has been done, but if someone is using (say) Oxygen 20, will they still need to have the original log4j path as well as these new ones, or have all recent Oxygens been updated to the replacement log4j files above?

**Comment by raducoravu** [comment]
@martindholmes indeed if you want the framework to work with any Oxygen version you would need to leave the reference to:

      ${oxygenHome}/lib/*log4j*.jar

and add the other references to the new logging jars used in Oxygen 24.1 instead of replacing the old reference to the log4j jar with them.

**Comment by martindholmes** [comment]
Thanks @raducoravu. If it's OK with you I'm going to ask you to check over my pull request before I merge the changes.

**Comment by martindholmes** [comment]
Now complete.
