### ISSUE TITLE
Entity encoding lost in PDF and ODT processing of jTEI egXMLs

### ISSUE THREAD

**Issue by martindholmes** [TEIC/oxygen-tei#6]
An egXML like this in a source article:

```
         <egXML xmlns="http://www.tei-c.org/ns/Examples">
            <pb facs="http://eebo.chadwyck.com/fetchimage?vid=13311&amp;page=2&amp;width=1200"/>
          </egXML>
```

will result in output that looks like this:

```
     <pb facs="http://eebo.chadwyck.com/fetchimage?vid=13311&page=2&width=1200"/>
```

where the ampersands appear unescaped in the output. It is arguable that the ampersands in the input should be doubly-escaped, and in fact this has the desired effect; if that is the correct procedure, we should document it in the jTEI ODD.

**Comment by martindholmes** [comment]
This happens not just in attribute values but also in text nodes, and it requires a fix be provided in Stylesheets/profiles/jtei/odt.common.xsl, around lines 634 and 644.

**Comment by martindholmes** [comment]
Fix for the ODT portion of this problem committed to the Stylesheets repo in 

https://github.com/TEIC/Stylesheets/commit/76524f91681780eb529abdffc6b511971f6b374e

**Comment by martindholmes** [comment]
Fix for the PDF portion of this bug committed to the Stylesheets repo in

https://github.com/TEIC/Stylesheets/commit/b470fe79d67c4dda91dbd53426fb6c5abff8179c

**Comment by martindholmes** [comment]
Waiting for builds and tests before closing. But there may be a bit more work to do:

My assumption is that ampersand, `<` and `>` inside an egXML-descendant text node or attribute value should be double escaped so that they appear as escapes in the output; I've ignored single and double quotes, because they don't need to be escaped in many situations, although it's possible we should look at doing double-quotes that appear in an attribute value, since the user might put this in:

~~~~~
<seg n='This is "annoying" really'>
~~~~~

which we'd then reproduce with double quotes as delimiters:

~~~~~
<seg n="This is "annoying" really">
~~~~~

which would be bad.

**Comment by rvdb** [comment]
I've fixed the remaining bug (escaping of double quotes in attribute values inside `<egXML>`) in this pull request: https://github.com/TEIC/Stylesheets/pull/189. That commit also harmonizes `<egXML>` processing in all 3 output formats (PDF, ODT, OpenEdition).
