### ISSUE TITLE
Time to remove P4 from the Oxygen framework?

### ISSUE THREAD

**Issue by martindholmes** [TEIC/oxygen-tei#8]
P4 in TEI has long been deprecated, and the P4 framework for Oxygen was marked as deprecated four years ago:

```
tweak script; make P4 marked as deprecated
sebastian.rahtz@gmail.com committed on Oct 14, 2012
```

I would like Council to discuss removing the entire P4 framework at this point.

**Comment by lb42** [comment]
Fine by me. We could remove that oxygen tei starter thing st the same time.

**Comment by martindholmes** [comment]
What tei starter thing?

**Comment by lb42** [comment]
The thing called "tei minimal" and its varieties. And we should add tei simple or whatever it winds up being called.

**Comment by martindholmes** [comment]
Minimal is in the TEI Exemplars; has Council decided to get rid of it? What's the difference between "bare" and "minimal"?

Simple never seems to settle down enough to be included; if its very name is in question now, after all these years of people talking about it and publishing about it, it seems further than ever from a practical release. I don't think it belongs in the Oxygen plugin until it's fully integrated into P5, and possibly the Stylesheets too.

**Comment by lb42** [comment]
At the last council meeting, it was agreed that Simple should be included in the next release, i.e. next month. We have also agreed to fix on a name for it next week.   Getting it into the plugin would be a definite step forward. I am not sure what you mean by "fully integrated into P5" : everything it contains has been in P5 since April this year, notably the Processing Model. It's as well supported by the Stylesheets as any other TEI exemplar,(with the honorable exception of TEI-journal which is indeed exemplary)

**Comment by lb42** [comment]
Bare is even more minimal than minimal. Minimal was invented by Sebastian as a minimal ODD , rather than a minimal schema, whichh I for one find very confusing. I dont think anyone uses it. But you're right, Council hasnt discussed dropping it as such.

**Comment by martindholmes** [comment]
@lb42: by "fully integrated" I meant included as an exemplar, listed here: 

http://www.tei-c.org/Guidelines/Customization/

(which "minimal" never was), and with any stylesheet handling that's required (such as processing of the private-uri `@rendition` values) added to the Stylesheets. If that's the target for the next release, that's great. I don't know why the name needs to be changed, but if it does, all those "simple:"-prefixed values will change, and I'll have to change a few projects where I already adopted them thinking they were settled. Why change the name, do you know?

**Comment by raducoravu** [comment]
👍 Next Oxygen version will be a major one (19.0) so good time to make changes which could break a little bit the backward compatibility with older TEI documents.

**Comment by jamescummings** [comment]
The only time people use Minimal is when then choose "Build Up" in TEI Roma.  I believe it was created for that purpose, to be a template starting ODD for further customisation, not a complete product in itself. I don't think it should be in the oxygen-tei framework really.

The only time I've used it as a schema is when teaching ODD customisation.

+1 for removing TEI P4 from the oxygen-tei framework.

**Comment by martindholmes** [comment]
This definitely needs a Council decision. I've written to TEI-L to see if anyone would miss it.

**Comment by martindholmes** [comment]
@raducoravu What's the timeline for Oxygen 19? It would be good if we could have all these proposed changes integrated and tested into a stable version of the plugin ready for that release.

**Comment by raducoravu** [comment]
@martindholmes Oxygen 19 should be released in May-June 2017.

**Comment by martindholmes** [comment]
Thanks @raducoravu, that's a very practical target. We could remove it from the bleeding-edge version of the plugin soon, then from the stable version in the first 2017 release of P5/Stylesheets; then it would be well-tested in time for the Oxygen release. @jamescummings, could you raise this with Council? I'll assign it to you, then you can assign it back to me if/when it gets approval.

**Comment by jamescummings** [comment]
As posted on tei-council mailing list, setting status:Go and assigning @martindholmes who has suggested he is willing to implement. If no negative comments, go ahead and implement in next couple days.

**Comment by lb42** [comment]
How about getting simpleprint in as well? That's already been agreed by council!

**Comment by jamescummings** [comment]
Yes, if changing the framework, might as well add that in as well, IMHO.

**Comment by lb42** [comment]
And fix issue #11 which looks bad! I can't find the template file Radu is referring to  but certainly the file tei_isofs.template file in Exemplars looks broken

**Comment by raducoravu** [comment]
To avoid duplication there seems to be a Linux shell script "update-and-upload.sh" which automatically downloads resources from:

https://sourceforge.net/projects/tei/
and that "tei-3.0.0.zip\xml\tei\custom\templates" is used renamed to be the TEI P5 templates folder in the framework. So the change would need to be done to that ZIP file.

**Comment by martindholmes** [comment]
I think the Simple thing should be a separate ticket.

**Comment by lb42** [comment]
Can't see why, but I have created one anyway.

**Comment by martindholmes** [comment]
Because I'd like to deal with things one at a time, in an organized way, or I get confused. :-)

**Comment by martindholmes** [comment]
I've merged branch noP4 at commit https://github.com/TEIC/oxygen-tei/commit/2127e65a60daafdf023a73febb3ed91a342e28f3 which has my first attempt at removing all P4-related stuff. The bleeding-edge Oxygen plugin built successfully, and installed in my Oxygen, and indeed there is no P4 stuff to be seen. Whether everything else still works will require some testing. If you have the bleeding-edge plugin installed, could you update it and start testing things when you have a chance?

**Comment by lb42** [comment]
I installed oxyGen 18.1, and updated to the bleeding edge plugin. If I look in .com.oxygenxml/extensions/v18.1/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/templates/
I see what appear to be the right folders (i.e. TEI JTEI, TEI P5 and TEI ODD only) 
However, for reasons I fail to understand, in oXygen itself, when I select "New" I am still seeing the old list of framework templates, including TEI P4 (Deprecated). How do I reset the list?

**Comment by martindholmes** [comment]
@lb42: There are two sources for the list of document types: the core framework distributed with Oxygen itself (which is the old stable one), and the bleeding-edge plugin you've installed. If you go to Options/Preferences/Document Type Association, you'll see that the core framework document types are marked (for some reason) with "External", while the ones from the bleeding-edge plugin are marked "Add-on". As long as you don't see any P4 items marked "Add-on", we're good. The next major release of Oxygen will hopefully be built with a new stable plugin which is based on the latest releases from all our repos, so the P4 options would disappear completely at that stage.

**Comment by lb42** [comment]
Ah, thanks for the clarification. That seems to have done the trick. And I see that simplePunt is there already!

**Comment by martindholmes** [comment]
Done and gone.
